name: Scheduler - call Vercel every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (UTC)
  workflow_dispatch:        # allows manual run

jobs:
  call-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        env:
          SCHEDULER_URL: ${{ secrets.SCHEDULER_URL }}
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X GET "$SCHEDULER_URL")
          echo "HTTP status: $STATUS"
          if [[ "$STATUS" -ge 400 ]]; then
            exit 1
          fi
